import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';

import { ProductService } from '../../../../../services/product.service';

@Component({
  selector: 'app-add-product',
  imports: [CommonModule, FormsModule],
  templateUrl: './add-product.component.html',
  styleUrl: './add-product.component.css',
})
export class AddProductComponent {

  constructor(
    private productService: ProductService
  ) {}

  // Product details
  product = {
    name: '',
    category: '',
    description: '',
    unitPrice: null as number | null,
    gst: 18,
    standardPackage: null as number | null,
    stockQuantity: 0,
    image: '',
    isActive: true
  };

  // Product ID generated by Firestore after saving
  productId: string | null = null;

  // Product categories
  categories = [
    'Gold Buckets',
    'Mugs',
    'Planters',
    'Containers'
  ];

  // Selected image preview
  selectedImage: string | null = null;

  // Handle image selection
  onImageSelected(event: Event) {

    const input = event.target as HTMLInputElement;

    if (input.files && input.files.length > 0) {

      const file = input.files[0];

      const reader = new FileReader();

      reader.onload = () => {

        this.selectedImage = reader.result as string;

        this.product.image = this.selectedImage;

      };

      reader.readAsDataURL(file);
    }
  }

  // Add product to Firestore
  async addProduct() {

    // Validate required fields
    if (
      !this.product.name.trim() ||
      !this.product.category ||
      this.product.unitPrice === null ||
      !Number.isFinite(this.product.unitPrice) ||
      this.product.unitPrice <= 0 ||
      !Number.isInteger(this.product.stockQuantity) ||
      this.product.stockQuantity < 0
    ) {

      alert(
        'Please enter a valid product name, category, unit price, and stock quantity.'
      );

      return;
    }

    try {

      console.log(
        'Product before Firestore:',
        this.product
      );

      // Save product to Firestore
      const result = await this.productService.addProduct({
        ...this.product,
        name: this.product.name.trim(),
        createdAt: new Date(),
        updatedAt: new Date()
      });

      // Store the generated Firestore document ID
      this.productId = result.id;

      console.log(
        'Product Added to Firestore:',
        result.id
      );

      alert(
        `Product added successfully!\nProduct ID: ${result.id}`
      );

      // Reset form after successful save
      this.resetForm();

    } catch (error) {

      console.error(
        'Error adding product:',
        error
      );

      alert(
        'Failed to add product. Please try again.'
      );
    }
  }

  // Reset form
  resetForm() {

    this.product = {
      name: '',
      category: '',
      description: '',
      unitPrice: null,
      gst: 18,
      standardPackage: null,
      stockQuantity: 0,
      image: '',
      isActive: true
    };

    this.selectedImage = null;

    this.productId = null;
  }
}